name: learn-github-actions
run-name: ${{ github.actor}} is learnig GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code...
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install Bats
        run: npm install -g bats
      - name: Get Bats version
        run: bats --version
