name: learn-github-actions # The name of the workflow
run-name: ${{ github.actor }} is learnig GitHub Actions # The name for workflow runs, which will appear in the list of workflow runs on your repository's "Actions" tab.
on:
  push:
    branches:
      - main
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code...
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install Bats
        run: npm install -g bats
      - name: Get Bats version
        run: bats --version
